title: Les Créations de Doudou
description: Couture sur mesure, Paris et ses environs
baseurl: ""
author:
  name: "Doudou Créations"
  email: "doudoucrea25@gmail.com"
theme: "minima"
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
defaults:
  - scope:
      path: "images"
    values:
      image: true
# Build settings
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - .gitignore
  - .DS_Store
